

import javax.swing.JOptionPane;

public class VentanaPrincipal extends javax.swing.JFrame {

    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initButton = new javax.swing.JButton();
        nueArcButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        pullButton = new javax.swing.JButton();
        pushButton = new javax.swing.JButton();
        commitButton = new javax.swing.JButton();
        btnWorkspace = new javax.swing.JButton();
        btnIndex = new javax.swing.JButton();
        btnLocalRepository = new javax.swing.JButton();
        btnRemoteRepository = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Repositorio");

        initButton.setText("Init");
        initButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initButtonActionPerformed(evt);
            }
        });

        nueArcButton.setText("Nuevo Archivo");
        nueArcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueArcButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        pullButton.setText("Pull");
        pullButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pullButtonActionPerformed(evt);
            }
        });

        pushButton.setText("Push");
        pushButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushButtonActionPerformed(evt);
            }
        });

        commitButton.setText("Commit");
        commitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitButtonActionPerformed(evt);
            }
        });

        btnWorkspace.setText("Workspace");
        btnWorkspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkspaceActionPerformed(evt);
            }
        });

        btnIndex.setText("Index");
        btnIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndexActionPerformed(evt);
            }
        });

        btnLocalRepository.setText("Local Repository");
        btnLocalRepository.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalRepositoryActionPerformed(evt);
            }
        });

        btnRemoteRepository.setText("Remote Repository");
        btnRemoteRepository.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoteRepositoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nueArcButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(initButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pullButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pushButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(commitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnWorkspace)
                        .addGap(18, 18, 18)
                        .addComponent(btnIndex, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLocalRepository)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoteRepository)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWorkspace)
                    .addComponent(btnIndex)
                    .addComponent(btnLocalRepository)
                    .addComponent(btnRemoteRepository))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initButton)
                    .addComponent(addButton)
                    .addComponent(commitButton))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nueArcButton)
                    .addComponent(pullButton)
                    .addComponent(pushButton))
                .addGap(40, 40, 40))
        );

        initButton.getAccessibleContext().setAccessibleName("initButton");
        nueArcButton.getAccessibleContext().setAccessibleName("newArcButton");
        addButton.getAccessibleContext().setAccessibleName("addButton");
        pullButton.getAccessibleContext().setAccessibleName("pullButton");
        pushButton.getAccessibleContext().setAccessibleName("pushButton");
        commitButton.getAccessibleContext().setAccessibleName("commitButton");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void commitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitButtonActionPerformed
        if(VariablesGlobales.repo == null){
            JOptionPane.showMessageDialog(null, "Debe crear un repositorio primero.");
            return;
        }
        (new CommitVent()).setVisible(true);
    }//GEN-LAST:event_commitButtonActionPerformed

    private void initButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initButtonActionPerformed
        // TODO add your handling code here:
        (new InitVent()).setVisible(true);
    }//GEN-LAST:event_initButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        if(VariablesGlobales.repo == null){
            JOptionPane.showMessageDialog(null, "Debe crear un repositorio primero.");
            return;
        }
        
        if(VariablesGlobales.repo.workspace.listaArchivos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe agregar archivos al Workspace primero.");
            return;
        }
                
        
        (new AddVent()).setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void nueArcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueArcButtonActionPerformed
        if(VariablesGlobales.repo == null){
            JOptionPane.showMessageDialog(null, "Debe crear un repositorio primero.");
            return;
        }
        (new NueArcVent()).setVisible(true);
    }//GEN-LAST:event_nueArcButtonActionPerformed

    private void pullButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pullButtonActionPerformed
        if(VariablesGlobales.repo == null){
            JOptionPane.showMessageDialog(null, "Debe crear un repositorio primero.");
            return;
        }
        
        VariablesGlobales.repo.pull(VariablesGlobales.repo);
        JOptionPane.showMessageDialog(null, "Pull Realizado.");
        
    }//GEN-LAST:event_pullButtonActionPerformed

    private void pushButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushButtonActionPerformed
        if(VariablesGlobales.repo == null){
            JOptionPane.showMessageDialog(null, "Debe crear un repositorio primero.");
            return;
        }
        VariablesGlobales.repo.push(VariablesGlobales.repo);
        JOptionPane.showMessageDialog(null, "Push Realizado.");
    }//GEN-LAST:event_pushButtonActionPerformed

    private void btnWorkspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkspaceActionPerformed
        if(VariablesGlobales.repo == null){
            JOptionPane.showMessageDialog(null, "Debe crear un repositorio primero.");
            return;
        }
        
        VentanaWorkspace ventana = new VentanaWorkspace();        
        ventana.setVisible(true);
        ventana.setTitle("Workspace");
        
        
    }//GEN-LAST:event_btnWorkspaceActionPerformed

    private void btnIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndexActionPerformed
        if(VariablesGlobales.repo == null){
            JOptionPane.showMessageDialog(null, "Debe crear un repositorio primero.");
            return;
        }
        
        VentanaIndex ventana = new VentanaIndex();        
        ventana.setVisible(true);
        ventana.setTitle("Index");        
    }//GEN-LAST:event_btnIndexActionPerformed

    private void btnLocalRepositoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalRepositoryActionPerformed
        if(VariablesGlobales.repo == null){
            JOptionPane.showMessageDialog(null, "Debe crear un repositorio primero.");
            return;
        }

        VentanaLocalRepo ventana = new VentanaLocalRepo();        
        ventana.setVisible(true);
        ventana.setTitle("Local Repository");        
    }//GEN-LAST:event_btnLocalRepositoryActionPerformed

    private void btnRemoteRepositoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoteRepositoryActionPerformed
        if(VariablesGlobales.repo == null){
            JOptionPane.showMessageDialog(null, "Debe crear un repositorio primero.");
            return;
        }
        
        VentanaRemoteRepo ventana = new VentanaRemoteRepo();        
        ventana.setVisible(true);
        ventana.setTitle("Remote repository");        
    }//GEN-LAST:event_btnRemoteRepositoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton btnIndex;
    private javax.swing.JButton btnLocalRepository;
    private javax.swing.JButton btnRemoteRepository;
    private javax.swing.JButton btnWorkspace;
    private javax.swing.JButton commitButton;
    private javax.swing.JButton initButton;
    private javax.swing.JButton nueArcButton;
    private javax.swing.JButton pullButton;
    private javax.swing.JButton pushButton;
    // End of variables declaration//GEN-END:variables

}
